version: "3.9"

services:
  mysqlDB:
    image: mysql:5.7
    ports:
      - 3307:3306
    restart: always
    environment:     
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: studentDB
      MYSQL_USER: sa
      MYSQL_PASSWORD: password    
    container_name: mysqlDB 

  mywebapp:
    image: webapp_img:latest
    ports:
      - 9090:9090
    restart: always
    depends_on:
      - mysqlDB
    links:
      - mysqlDB
    container_name: mywebapp
        
  

 
        
        